name: Compilation test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ ninja-build

      - name: Configure CMake
        run: |
        mkdir build
        cmake -S . -B build -G Ninja

      - name: Build
        run: cmake --build build

