name: Compilation test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          submodules: true


      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ python3 libgl-dev libgl1-mesa-dev \
            libx11-xcb-dev libfontenc-dev libice-dev libsm-dev libxaw7-dev \
            libxcomposite-dev libxcursor-dev libxdamage-dev libxext-dev \
            libxfixes-dev libxi-dev libxinerama-dev libxkbfile-dev libxmu-dev \
            libxmuu-dev libxpm-dev libxrandr-dev libxrender-dev libxres-dev \
            libxss-dev libxt-dev libxtst-dev libxv-dev libxxf86vm-dev \
            libxcb-glx0-dev libxcb-render0-dev libxcb-render-util0-dev \
            libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev \
            libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev \
            libxcb-sync-dev libxcb-sync-dev libxcb-xfixes0-dev \
            libxcb-xinerama0-dev libxcb-dri3-dev uuid-dev libxcb-cursor-dev \
            libxcb-dri2-0-dev libxcb-dri3-dev libxcb-present-dev \
            libxcb-composite0-dev libxcb-ewmh-dev libxcb-res0-dev \
            libxcb-util-dev libxcb-util0-dev

      - name: Install dependencies (MacOS)
        if: runner.os == 'macOS'
        run: brew install cmake python

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes
          choco install python --yes


      - name: Install Conan
        run: pip install conan


      # We cache the Conan packages, especially since it takes a painful amount
      # of time to install and build Skia, also the packages rarely ever change
      # and if they change, it can easily be updated by simply deleting the
      # cache
      - name: Cache Conan dependencies
        uses: actions/cache@v4
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-conan-${{ hashFiles('conanfile.*') }}
          restore-keys: |
            ${{ runner.os }}-conan-


      - name: Configure Conan
        run: conan profile detect --force


      - name: Export local Conan recipes
        run: >
          conan export conan_extern/conan-skia/recipes/skia/all
          --name=skia
          --version=138.20250708.0


      - name: Install Conan dependencies
        run: >
          conan install .
          --output-folder=build
          --build=missing
          -s build_type=Release
          -s compiler.cppstd=17


      - name: Clean unnecessary Conan cache
        run: conan cache clean "*" --build --source --download


      - name: Configure CMake
        run: >
          cmake -S . -B build
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_TOOLCHAIN_FILE="build/conan_toolchain.cmake"


      - name: Build
        run: cmake --build build --config Release

