name: Compare images

on:
  workflow_run:
    workflows: ["App test"]
    types:
      - completed

jobs:
  compare:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4


      - name: Install system packages
        run: |
          sudo apt update
          sudo apt install python3


      - name: Install python packages
        run: python -m pip install Wand
            

      - name: Download images
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}


      - name: Run comparison test
        run: python test/golden_test.py test text_test
