name: App test

on:
  workflow_run:
    workflows: ["Compilation test"]
    types:
      - completed

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4


      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ runner.os }}-build


      - name: Decompress build artifacts
        run: tar -xvf build.tar


      - name: Run (Linux & MacOS)
        if: runner.os != 'Windows'
        run: build/test ${{ runner.os }}.png


      - name: Run (Windows)
        if: runner.os != 'Windows'
        run: build/Release/test ${{ runner.os }}.png


      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-image
          path: ${{ runner.os }}.png